version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rssagg
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env  # Load the .env file
    environment:
      DB_URL: postgres://u6juess7u9gn7c:p68f29df82e04941bed676600d03c4339bb628b7e7f6a2608f7c62cddd5b56534@c3nv2ev86aje4j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d3ej44bt3645pe
