version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rssagg
    ports:
      - "5432:5432"
    # Note: You don't need to modify the db service as we are using the Render DB for the backend
  
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env  # Load the .env file
    environment:
      # Ensure that the backend uses the Render database connection
      DB_URL: ${DATABASE_URL}
